on:
  push:
    branches:
      - 'releases/*'
  pull_request:
    branches:
      - 'releases/*'
jobs: 
    trigger-integration-tests:
      name: Trigger Integration tests
      runs-on: ubuntu-latest
      steps:
        - name: Trigger Test run
          env:
           repname: ${env:GITHUB_REPOSITORY};
          run: | 
           echo ">> ${{github.repository}}"
           curl -X POST -H "Authorization: token ${{ secrets.L2_REPO_TOKEN }}" https://api.github.com/repos/rgsubh/l2-integration-tests/dispatches --data '{"event_type": "K8sCreateSecret", "client_payload": {"action": "CreateSecret", "commit": "${{ github.sha }}", "branch": "${{ github.event.pull_request.base.ref }}", "PR_NUMBER": "${{ github.event.pull_request.number }}", "GITHUB_REPOSITORY":  "rgsubh/k8s-create-secret", "frombranch": "${{ github.event.pull_request.head.ref }}" }}'
         